uploads = []
generated = []

[[outputs]]
id = "Upel7fQBbXrwZ9hdDrxNn"
uri = "file://anonymiketech-pterodactyl.tar.gz"
type = "unspecified"
title = "ANONYMIKETECH Pterodactyl Release (3.8 MB)"

[[outputs]]
id = "iIQZvtqdoZuxqzNVbzc-L"
uri = "file://anonymiketech-panel.zip"
type = "unspecified"
title = "anonymiketech-panel.zip — logout fix + grant feature + TRUTH MD naming"
